### ISSUE TITLE
你好，请问可以发送excle这样的文件嘛？

### ISSUE THREAD

**Issue by aluckydog0716** [seoktaehyeon/work-weixin-robot#1]

**Comment by bxwillshi** [comment]
是excel吗？企业微信的官网上并不支持发送文件，可以尝试用在线excel，然后用markdown格式发送链接

**Comment by aluckydog0716** [comment]
感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Will <notifications@github.com&gt;
发送时间: 2020年7月24日 20:13
收件人: seoktaehyeon/work-weixin-robot <work-weixin-robot@noreply.github.com&gt;
抄送: Jerry_ym <1203078658@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[seoktaehyeon/work-weixin-robot] 你好，请问可以发送excle这样的文件嘛？ (#1)
